(()=>{
  'use strict';
  const KEY='newtk-v01';
  const defaults={route:'welcome',tab:'home',concern:'groceries',state:'Selangor',household:'4',verified:false,consents:[],largeText:false};
  const saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}})();
  const state={...defaults,...saved};
  const app=document.querySelector('#app');

  const concerns={
    groceries:{icon:'◫',label:'Belanja dapur',desc:'Harga barang asas, SARA dan pilihan berhampiran.'},
    fuel:{icon:'◉',label:'Petrol & perjalanan',desc:'Subsidi bahan api dan anggaran perjalanan.'},
    bills:{icon:'▤',label:'Bil & rumah',desc:'Keutamaan bil, perumahan dan bantuan berkaitan.'},
    children:{icon:'☆',label:'Anak & sekolah',desc:'Keperluan pendidikan dan perbelanjaan keluarga.'},
    income:{icon:'◇',label:'Kerja & pendapatan',desc:'Program pekerjaan, latihan dan sokongan pendapatan.'},
    urgent:{icon:'!',label:'Bantuan segera',desc:'Saluran rasmi apabila keadaan memerlukan perhatian.'}
  };
  const sources={
    sara:{name:'SARA / MyKasih',scope:'Baki, kemas kini terakhir dan transaksi ringkas',url:'https://sara.gov.my/'},
    budi:{name:'BUDI95',scope:'Status dan penggunaan subsidi bahan api',url:'https://www.budi95.gov.my/'},
    str:{name:'STR / HASiL',scope:'Status permohonan dan bayaran',url:'https://bantuantunai.hasil.gov.my/'}
  };
  function save(){localStorage.setItem(KEY,JSON.stringify(state));document.documentElement.classList.toggle('large-text',state.largeText)}
  function phase(){return `<div class="phase"><b>PROTOTAIP v0.1</b> Data peribadi dan baki yang dipaparkan selepas log masuk ialah simulasi. <a href="#" data-action="about-demo">Ketahui batas prototaip</a></div>`}
  function top(){return `<header class="topbar"><div class="brand"><div class="brand-mark" aria-hidden="true">TK</div><div><b>TenangKITA</b><small>Ringkaskan bantuan. Kecilkan beban.</small></div></div><button class="icon-button" data-action="toggle-text" aria-label="Tukar saiz teks">Aa</button></header>`}
  function shell(content,nav=true){return `${phase()}${top()}<main id="main" tabindex="-1">${content}</main>${nav?tabs():''}`}
  function tabs(){const items=[['home','⌂','Utama'],['benefits','▣','Bantuan'],['needs','◎','Keperluan'],['me','○','Saya']];return `<nav class="tabs" aria-label="Navigasi utama">${items.map(([id,icon,label])=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}" ${state.tab===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</button>`).join('')}</nav>`}
  function welcome(){return shell(`<section class="card hero"><div class="hero-symbol" aria-hidden="true">♥</div><p class="eyebrow">Untuk rakyat Malaysia</p><h1>Apa yang boleh kita ringankan hari ini?</h1><p>TenangKITA membantu anda memahami bantuan, kos harian dan tindakan praktikal tanpa bahasa yang menghukum.</p><div class="button-row"><button class="button full" data-route="concern">Mulakan</button><button class="button-secondary full" data-action="guest">Teroka tanpa log masuk</button></div></section><section class="card"><h2>Apa yang TenangKITA lakukan</h2><div class="action-list"><article class="action"><span class="action-icon">1</span><div><b>Ringkaskan keadaan</b><small>Tunjukkan perkara paling penting dahulu.</small></div></article><article class="action"><span class="action-icon">2</span><div><b>Cadangkan tindakan kecil</b><small>Fokus pada apa yang boleh dibuat hari ini atau minggu ini.</small></div></article><article class="action"><span class="action-icon">3</span><div><b>Hubungkan sumber rasmi</b><small>Anda mengawal sumber yang disambungkan.</small></div></article></div></section>`,false)}
  function concern(){const places=['Selangor','Johor','Kedah','Sabah','Sarawak','W.P. Kuala Lumpur','Pulau Pinang','Perak','Kelantan','Terengganu','Negeri Sembilan','Melaka','Pahang','Perlis','W.P. Putrajaya','W.P. Labuan'];return shell(`<section class="card"><p class="eyebrow">Langkah 1 daripada 1</p><h1>Apa yang paling membimbangkan anda?</h1><p>Pilih satu dahulu. Anda boleh menukarnya kemudian.</p><div class="choice-grid">${Object.entries(concerns).map(([id,c])=>`<button class="choice ${state.concern===id?'selected':''}" data-concern="${id}" aria-pressed="${state.concern===id}"><span aria-hidden="true">${c.icon}</span><span><b>${c.label}</b><small>${c.desc}</small></span></button>`).join('')}</div><label class="field">Negeri atau wilayah<select id="state-select">${places.map(x=>`<option ${x===state.state?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Bilangan ahli isi rumah (pilihan)<select id="household-select">${['1','2','3','4','5','6+'].map(x=>`<option ${x===state.household?'selected':''}>${x}</option>`).join('')}</select></label><div class="privacy">Maklumat umum digunakan untuk cadangan yang lebih sesuai. TenangKITA tidak memerlukan lokasi tepat atau pendapatan untuk meneruskan.</div><button class="button full" data-action="finish-setup">Lihat cadangan saya</button></section>`,false)}
  function home(){const c=concerns[state.concern];const connected=state.verified&&state.consents.length;return `<section class="card hero"><p class="eyebrow">Ringkasan anda hari ini</p><h1>Kita fokus pada ${c.label.toLowerCase()} dahulu.</h1><p>Tidak perlu semak semuanya sekarang. Mulakan dengan satu tindakan kecil yang paling sesuai.</p><button class="button" data-tab-jump="benefits">${connected?'Lihat bantuan saya':'Sambungkan bantuan saya'}</button></section><section class="card"><h2>Tindakan minggu ini</h2><div class="action-list">${weeklyActions().map((a,i)=>`<article class="action"><span class="action-icon">${i+1}</span><div><b>${a[0]}</b><small>${a[1]}</small></div></article>`).join('')}</div></section><section class="card"><h2>Status ringkas</h2><div class="status-grid"><article class="mini-card"><span>Lokasi umum</span><b>${state.state}</b></article><article class="mini-card"><span>Ahli isi rumah</span><b>${state.household}</b></article><article class="mini-card"><span>Sumber disambung</span><b>${state.consents.length}</b></article></div><div class="notice">Anggaran dan cadangan mestilah disahkan melalui sumber rasmi sebelum membuat keputusan kewangan.</div></section>`}
  function weeklyActions(){const common=['Semak bantuan yang berkaitan','Lihat SARA, STR dan bantuan lain tanpa membuat andaian kelayakan.'];const map={groceries:[['Rancang barang asas dahulu','Gunakan baki bantuan yang disahkan untuk barangan layak sebelum menggunakan tunai.'],['Semak pilihan berhampiran','Bandingkan harga dan jadual Jualan Rahmah sebelum bergerak.'],common],fuel:[['Semak penggunaan bahan api','Lihat penggunaan yang disahkan sebelum merancang perjalanan minggu ini.'],['Gabungkan perjalanan','Kurangkan perjalanan berulang jika praktikal dan selamat.'],common],bills:[['Susun bil mengikut tarikh','Mulakan dengan bil yang mempunyai tarikh paling hampir.'],common,['Simpan sedikit ruang kecemasan','Anggaran kecil tetap boleh membantu apabila ada perubahan.']],children:[['Fokus keperluan minggu ini','Asingkan keperluan sekolah yang perlu didahulukan.'],common,['Semak bantuan negeri','Program pendidikan boleh berbeza mengikut negeri.']],income:[['Semak program berkaitan kerja','Cari latihan atau insentif mengikut keadaan pekerjaan.'],common,['Pilih satu tindakan','Kemas kini satu permohonan atau dokumen dahulu.']],urgent:[['Utamakan keselamatan','Jika ada bahaya segera, hubungi 999 atau saluran rasmi berkaitan.'],['Hubungi bantuan manusia','Dapatkan bantuan JKM, Talian Kasih atau pihak berkuasa tempatan.'],['Maklumkan keluarga dipercayai','Kongsi lokasi dan keadaan apabila selamat berbuat demikian.']]};return map[state.concern]||map.groceries}
  function benefits(){if(!state.verified)return `<section class="card hero"><p class="eyebrow">Bantuan peribadi</p><h1>Lihat maklumat anda dengan selamat.</h1><p>Log masuk hanya diperlukan untuk melihat status, baki atau penggunaan yang berkaitan dengan diri anda.</p><div class="privacy"><b>TenangKITA tidak meminta kata laluan MyDigital ID.</b><br>Pengesahan berlaku dalam aplikasi MyDigital ID.</div><button class="button full" data-route="auth-intro">Log masuk dengan MyDigital ID</button><button class="button-secondary full" data-action="official-only">Teruskan ke semakan rasmi</button></section>${publicBenefits()}`;return `<div class="demo-banner">DATA DEMO — Bukan baki, transaksi atau keputusan sebenar.</div><section class="card"><h1>Bantuan saya</h1><p>Hanya sumber yang anda izinkan dipaparkan. Anda boleh menarik balik izin pada bila-bila masa.</p>${Object.keys(sources).map(benefitCard).join('')}</section>`}
  function publicBenefits(){return `<section class="card"><h2>Boleh diteroka tanpa log masuk</h2><div class="action-list"><article class="action"><span class="action-icon">✓</span><div><b>Portal SARA</b><small>Syarat, barangan dan kedai terpilih.</small></div></article><article class="action"><span class="action-icon">✓</span><div><b>Portal STR</b><small>Maklumat dan semakan rasmi HASiL.</small></div></article><article class="action"><span class="action-icon">✓</span><div><b>Program negeri</b><small>Cadangan berdasarkan negeri pilihan anda.</small></div></article></div></section>`}
  function benefitCard(id){const s=sources[id],on=state.consents.includes(id);const data={sara:['Baki demo','RM84.50','Dikemas kini: simulasi hari ini'],budi:['Penggunaan demo','42 L bulan ini','Had dan kaedah sebenar tertakluk sumber rasmi'],str:['Status demo','Bayaran dikreditkan','Tarikh dan jumlah sebenar melalui HASiL']}[id];return `<article class="benefit"><div class="benefit-head"><div><h3>${s.name}</h3><span class="tag ${on?'connected':''}">${on?'Disambungkan':'Belum diizinkan'}</span></div><span class="tag demo">Demo</span></div>${on?`<div class="benefit-data"><small>${data[0]}</small><strong>${data[1]}</strong><small>${data[2]}</small></div>`:`<p>${s.scope}</p>`}<div class="meta">Sumber: ${s.name} · Tahap: ${on?'Identiti disahkan, data simulasi':'Semakan awam'}</div><div class="inline-actions">${on?`<button class="text-button" data-disconnect="${id}">Tarik balik izin</button>`:`<button class="button-secondary" data-connect="${id}">Beri izin</button>`}<a class="link button-secondary" href="${s.url}" target="_blank" rel="noopener noreferrer">Semak rasmi</a></div></article>`}
  function needs(){return `<section class="card"><h1>Keperluan harian</h1><p>Maklumat awam dan alat mudah yang tidak memerlukan identiti anda.</p><div class="choice-grid"><article class="choice"><span aria-hidden="true">▣</span><span><b>Harga barang asas</b><small>Lapisan data harga memerlukan sumber langsung dan masa kemas kini.</small></span></article><article class="choice"><span aria-hidden="true">◎</span><span><b>Jualan Rahmah</b><small>Jadual mengikut lokasi akan dipaparkan selepas integrasi rasmi.</small></span></article><article class="choice"><span aria-hidden="true">◇</span><span><b>Kalkulator perjalanan</b><small>Anggaran sahaja; tiada data perjalanan disimpan dalam v0.1.</small></span></article></div></section><section class="card"><h2>Saluran bantuan manusia</h2><p>TenangKITA tidak sepatutnya memaksa rakyat menyelesaikan semuanya secara digital.</p><div class="action-list"><article class="action"><span class="action-icon">☎</span><div><b>Talian Kasih 15999</b><small>Sokongan kebajikan dan isu sosial.</small></div></article><article class="action"><span class="action-icon">!</span><div><b>Kecemasan 999</b><small>Untuk bahaya atau kecemasan segera.</small></div></article></div></section>`}
  function me(){return `<section class="card"><h1>Saya & privasi</h1><div class="setting-row"><div><b>Saiz teks lebih besar</b><small>Mudahkan pembacaan pada peranti kecil.</small></div><button class="button-secondary" data-action="toggle-text">${state.largeText?'Tutup':'Aktifkan'}</button></div><div class="setting-row"><div><b>Keutamaan utama</b><small>${concerns[state.concern].label}</small></div><button class="text-button" data-route="concern">Tukar</button></div><div class="setting-row"><div><b>Status identiti</b><small>${state.verified?'Disahkan dalam simulasi MyDigital ID':'Belum disahkan'}</small></div><span class="tag ${state.verified?'connected':''}">${state.verified?'Disahkan':'Tetamu'}</span></div></section><section class="card"><h2>Pusat izin</h2>${Object.entries(sources).map(([id,s])=>`<div class="setting-row"><div><b>${s.name}</b><small>${state.consents.includes(id)?'Izin aktif':'Tidak disambungkan'}</small></div>${state.consents.includes(id)?`<button class="text-button" data-disconnect="${id}">Tarik balik</button>`:'<span class="tag">Tiada akses</span>'}</div>`).join('')}</section><section class="card"><h2>Kawalan data</h2><p>v0.1 menyimpan pilihan prototaip pada peranti ini sahaja.</p><button class="button-secondary danger-button full" data-action="reset">Padam data prototaip</button></section>`}
  function authIntro(){return shell(`<section class="card"><div class="auth-logo" aria-hidden="true">ID</div><p class="eyebrow">Pengesahan identiti</p><h1>Log masuk melalui MyDigital ID</h1><p>Anda akan dibawa ke aplikasi MyDigital ID. Selepas pengesahan, anda akan kembali ke TenangKITA.</p><div class="privacy"><b>Maklumat yang diperlukan:</b><br>Nama paparan, pengenal bertoken dan status pengesahan. Kata laluan atau biometrik tidak diberikan kepada TenangKITA.</div><div class="button-row"><button class="button full" data-action="start-auth">Teruskan ke MyDigital ID</button><button class="button-secondary full" data-tab-jump="benefits">Batal</button></div></section>`,false)}
  function authProgress(){return shell(`<section class="card auth-progress"><div class="spinner" aria-hidden="true"></div><h1>Membuka MyDigital ID…</h1><p>Dalam aplikasi sebenar, sahkan menggunakan kata laluan atau biometrik pada peranti anda.</p><div class="demo-banner">SIMULASI — Tiada aplikasi luar dibuka dan tiada identiti sebenar digunakan.</div></section>`,false)}
  function consent(){return shell(`<section class="card"><p class="eyebrow">Identiti berjaya disahkan — simulasi</p><h1>Pilih maklumat yang boleh dibaca</h1><p>MyDigital ID mengesahkan identiti. Izin data manfaat diberikan secara berasingan kepada setiap sumber.</p>${Object.entries(sources).map(([id,s])=>`<article class="consent-item"><label><input type="checkbox" value="${id}" class="consent-check"><span>${s.name}<small>${s.scope}. Akses baca sahaja; tiada permohonan atau rekod diubah.</small></span></label></article>`).join('')}<div class="privacy">Anda boleh menarik balik izin kemudian dalam “Saya & privasi”.</div><button class="button full" data-action="approve-consent">Simpan pilihan dan teruskan</button><button class="button-secondary full" data-action="skip-consent">Terus tanpa sambungan</button></section>`,false)}
  function main(){const view={home,benefits,needs,me}[state.tab]||home;return shell(view())}
  function about(){alert('NewTenangKITA v0.1 ialah prototaip. MyDigital ID dan data manfaat adalah simulasi; tiada kelayakan, baki atau transaksi sebenar diproses.')}
  function render(){save();const routes={welcome,concern,'auth-intro':authIntro,'auth-progress':authProgress,consent,main};app.innerHTML=(routes[state.route]||main)();bind();window.scrollTo(0,0)}
  function bind(){
    document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>{state.route=el.dataset.route;render()});
    document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.tab;state.route='main';render()});
    document.querySelectorAll('[data-tab-jump]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.tabJump;state.route='main';render()});
    document.querySelectorAll('[data-concern]').forEach(el=>el.onclick=()=>{state.concern=el.dataset.concern;render()});
    document.querySelectorAll('[data-action="toggle-text"]').forEach(el=>el.onclick=()=>{state.largeText=!state.largeText;render()});
    document.querySelectorAll('[data-action="about-demo"]').forEach(el=>el.onclick=e=>{e.preventDefault();about()});
    const setup=document.querySelector('[data-action="finish-setup"]');if(setup)setup.onclick=()=>{state.state=document.querySelector('#state-select').value;state.household=document.querySelector('#household-select').value;state.route='main';state.tab='home';render()};
    const guest=document.querySelector('[data-action="guest"]');if(guest)guest.onclick=()=>{state.route='main';render()};
    const auth=document.querySelector('[data-action="start-auth"]');if(auth)auth.onclick=()=>{state.route='auth-progress';render();setTimeout(()=>{state.route='consent';render()},1200)};
    const approve=document.querySelector('[data-action="approve-consent"]');if(approve)approve.onclick=()=>{state.verified=true;state.consents=[...document.querySelectorAll('.consent-check:checked')].map(x=>x.value);state.route='main';state.tab='benefits';render()};
    const skip=document.querySelector('[data-action="skip-consent"]');if(skip)skip.onclick=()=>{state.verified=true;state.consents=[];state.route='main';state.tab='benefits';render()};
    document.querySelectorAll('[data-connect]').forEach(el=>el.onclick=()=>{state.consents=[...new Set([...state.consents,el.dataset.connect])];render()});
    document.querySelectorAll('[data-disconnect]').forEach(el=>el.onclick=()=>{state.consents=state.consents.filter(x=>x!==el.dataset.disconnect);render()});
    const official=document.querySelector('[data-action="official-only"]');if(official)official.onclick=()=>window.open('https://www.malaysia.gov.my/','_blank','noopener');
    const reset=document.querySelector('[data-action="reset"]');if(reset)reset.onclick=()=>{if(confirm('Padam semua pilihan prototaip pada peranti ini?')){localStorage.removeItem(KEY);Object.assign(state,defaults);render()}};
  }
  document.documentElement.classList.toggle('large-text',state.largeText);
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
  render();
})();
